/*
 * Copyright 2017 Andres.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.eljavatar.swingutils.core.components;

import com.eljavatar.swingutils.core.modelcomponents.TableModelGeneric;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author Andres
 * @param <T>
 */
public class LazyJTable<T> extends javax.swing.JPanel {

    /**
     * Creates new form LazyJTable
     */
    public LazyJTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPlistData = new javax.swing.JScrollPane();
        jTlistData = new javax.swing.JTable();
        jBfirst = new javax.swing.JButton();
        jBprev = new javax.swing.JButton();
        jBnext = new javax.swing.JButton();
        jBlast = new javax.swing.JButton();

        jTlistData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSPlistData.setViewportView(jTlistData);

        jBfirst.setText("<<");

        jBprev.setText("<");

        jBnext.setText(">");

        jBlast.setText(">>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPlistData)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBfirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBprev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBnext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBlast)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSPlistData, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBfirst)
                    .addComponent(jBprev)
                    .addComponent(jBnext)
                    .addComponent(jBlast))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBfirst;
    private javax.swing.JButton jBlast;
    private javax.swing.JButton jBnext;
    private javax.swing.JButton jBprev;
    private javax.swing.JScrollPane jSPlistData;
    private javax.swing.JTable jTlistData;
    // End of variables declaration//GEN-END:variables

    public JTable getjTlistData() {
        return jTlistData;
    }

    public void setjTlistData(JTable jTlistData) {
        this.jTlistData = jTlistData;
    }

    public TableModelGeneric getTableModel() {
        return (TableModelGeneric) jTlistData.getModel();
    }
    
    public void setTableModel(TableModelGeneric tableModelGeneric) {
        this.jTlistData.setModel(tableModelGeneric);
    }
    
    public List<T> getListData() {
        return getTableModel().getListElements();
    }
    
    public void setListData(List<T> listData) {
        getTableModel().setListElements(listData);
        getTableModel().fireTableDataChanged();
    }
    
}
